# Generated by Django 4.2.7 on 2023-12-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
        migrations.RenameField(
            model_name='generalsetting',
            old_name='created_date',
            new_name='created_date',
        ),
    ]
