# Generated by Django 4.2.7 on 2024-08-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
